In [49]:
import pandas as pd
import numpy as np

# Pandas

## Creation of Dataframe

In [50]:
#Creation by numpy
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Colum1","Colum2","Colum3","Colum4"])
df

      Colum1  Colum2  Colum3  Colum4
Row1       0       1       2       3
Row2       4       5       6       7
Row3       8       9      10      11
Row4      12      13      14      15
Row5      16      17      18      19

# Eporting

In [51]:
# To Csv

df.to_csv('trialOutput.csv')

# Reteriaval Of Value

In [52]:
df.loc['Row1']

Colum1    0
Colum2    1
Colum3    2
Colum4    3
Name: Row1, dtype: int64

In [53]:
type(df.loc[:,'Colum1'])

pandas.Series

In [54]:
df.iloc[0]

Colum1    0
Colum2    1
Colum3    2
Colum4    3
Name: Row1, dtype: int64

In [55]:
df.iloc[:,:]

      Colum1  Colum2  Colum3  Colum4
Row1       0       1       2       3
Row2       4       5       6       7
Row3       8       9      10      11
Row4      12      13      14      15
Row5      16      17      18      19

In [56]:
df.iloc[1,2]

np.int64(6)

In [57]:
df.iloc[0:3]

      Colum1  Colum2  Colum3  Colum4
Row1       0       1       2       3
Row2       4       5       6       7
Row3       8       9      10      11

In [58]:
df.iloc[:,0:2]

      Colum1  Colum2
Row1       0       1
Row2       4       5
Row3       8       9
Row4      12      13
Row5      16      17

In [59]:
type(np.array(df.columns[-2:]))

numpy.ndarray

In [60]:
np.array(df.loc[['Row1','Row2'],df.columns[-2:]]).shape

(2, 2)

In [61]:
data = [
    ["Alice", 25, 50000],
    ["Bob",   30, 60000],
    ["Charlie", 35, 70000]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Salary"])

In [62]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [63]:
diction={
    "Names": ["Ritik","Parth","Ronit"],
    "Age":[26,26,20],
    "Ocuupation":["Engineer","Sales","Marketing"]
}

df=pd.DataFrame(data=diction)
df

   Names  Age Ocuupation
0  Ritik   26   Engineer
1  Parth   26      Sales
2  Ronit   20  Marketing

In [64]:
rows,columns=list(df.shape)

In [65]:
rows

3

In [66]:
#old way
employee=[]
rows=30
showee=[f"Employee{i}" for i in range(rows)]



showee

['Employee0',
 'Employee1',
 'Employee2',
 'Employee3',
 'Employee4',
 'Employee5',
 'Employee6',
 'Employee7',
 'Employee8',
 'Employee9',
 'Employee10',
 'Employee11',
 'Employee12',
 'Employee13',
 'Employee14',
 'Employee15',
 'Employee16',
 'Employee17',
 'Employee18',
 'Employee19',
 'Employee20',
 'Employee21',
 'Employee22',
 'Employee23',
 'Employee24',
 'Employee25',
 'Employee26',
 'Employee27',
 'Employee28',
 'Employee29']

In [67]:
[i*2 for i in range(5)]

[0, 2, 4, 6, 8]

In [68]:
df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam"],
    "Age":        [26, 26, 20, 28, 22],
    "Occupation": ["Engineer", "Sales", "Marketing", "Engineer", "Sales"],
    "Salary":     [70000, 50000, 45000, 80000, 48000]
})

In [69]:
df.shape        # → (5, 4)  means 5 rows, 4 columns
df.shape[0]     # → 5  (just rows)
df.shape[1]     # → 4  (just columns)

4

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       5 non-null      str
 1   Age         5 non-null      int64
 2   Occupation  5 non-null      str
 3   Salary      5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [71]:
df['Names'].value_counts

<bound method IndexOpsMixin.value_counts of 0    Ritik
1    Parth
2    Ronit
3    Diana
4      Sam
Name: Names, dtype: str>

In [72]:
data={
    "Names":["Ritik","Rohan","parth"],
    "Grade": ["A","B","A"],
    "Score": [100,200,50]
}

df = pd.DataFrame(data=data)
rows=df.shape[0]
df.index=[f"student{i}" for i in range(rows)]
df

          Names Grade  Score
student0  Ritik     A    100
student1  Rohan     B    200
student2  parth     A     50

In [73]:
df.iloc[-2:,:]

          Names Grade  Score
student1  Rohan     B    200
student2  parth     A     50

In [74]:
df.iloc[0]

Names    Ritik
Grade        A
Score      100
Name: student0, dtype: object

In [75]:
df.iloc[0:,-2:]

         Grade  Score
student0     A    100
student1     B    200
student2     A     50

In [76]:
np.array(df['Score'],dtype=float)

array([100., 200.,  50.])

In [77]:
[i*i for i in range(0,10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [78]:
[i.upper() for i in df['Names']]

['RITIK', 'ROHAN', 'PARTH']

In [79]:
[i for i in df['Score'] if i>=70]

[100, 200]

In [80]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, student0 to student2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   3 non-null      str
 1   Grade   3 non-null      str
 2   Score   3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0+ bytes

In [81]:
df.describe()

            Score
count    3.000000
mean   116.666667
std     76.376262
min     50.000000
25%     75.000000
50%    100.000000
75%    150.000000
max    200.000000

In [82]:
df.dtypes

Names      str
Grade      str
Score    int64
dtype: object

In [83]:
df

          Names Grade  Score
student0  Ritik     A    100
student1  Rohan     B    200
student2  parth     A     50

In [84]:
import pandas as pd

df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam"],
    "Age":        [26, 26, 20, 28, 22],
    "Occupation": ["Engineer", "Sales", "Marketing", "Engineer", "Sales"],
    "Salary":     [70000, 50000, 45000, 80000, 48000]
})

In [85]:
df

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
1  Parth   26      Sales   50000
2  Ronit   20  Marketing   45000
3  Diana   28   Engineer   80000
4    Sam   22      Sales   48000

In [86]:
df[df['Salary'] > 50000]

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
3  Diana   28   Engineer   80000

In [87]:
df[(df["Age"] > 22) & (df["Salary"] < 70000)]

   Names  Age Occupation  Salary
1  Parth   26      Sales   50000

In [88]:
df[(df["Occupation"] == "Engineer") | (df["Occupation"] == "Marketing")]

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
2  Ronit   20  Marketing   45000
3  Diana   28   Engineer   80000

In [89]:
df[df['Occupation'].isin(["Engineer","Marketing"])]

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
2  Ronit   20  Marketing   45000
3  Diana   28   Engineer   80000

In [90]:
df[~(df['Occupation'] == "Sales")]

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
2  Ronit   20  Marketing   45000
3  Diana   28   Engineer   80000

In [91]:
df[df['Age'].between(22,26)]

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
1  Parth   26      Sales   50000
4    Sam   22      Sales   48000

In [92]:
df

   Names  Age Occupation  Salary
0  Ritik   26   Engineer   70000
1  Parth   26      Sales   50000
2  Ronit   20  Marketing   45000
3  Diana   28   Engineer   80000
4    Sam   22      Sales   48000

In [93]:
df['bonus']=500

In [94]:
df

   Names  Age Occupation  Salary  bonus
0  Ritik   26   Engineer   70000    500
1  Parth   26      Sales   50000    500
2  Ronit   20  Marketing   45000    500
3  Diana   28   Engineer   80000    500
4    Sam   22      Sales   48000    500

In [95]:
df['bonus']=df['Salary']*0.1

In [96]:
df

   Names  Age Occupation  Salary   bonus
0  Ritik   26   Engineer   70000  7000.0
1  Parth   26      Sales   50000  5000.0
2  Ronit   20  Marketing   45000  4500.0
3  Diana   28   Engineer   80000  8000.0
4    Sam   22      Sales   48000  4800.0

In [ ]:
df.insert(1, "Department", ["IT", "Biz", "Mkt", "IT", "Biz"])
#          ↑      ↑                ↑
#        position  name          valuesokay nex

In [98]:
df

   Names Department  Age Occupation  Salary   bonus
0  Ritik         IT   26   Engineer   70000  7000.0
1  Parth        Biz   26      Sales   50000  5000.0
2  Ronit        Mkt   20  Marketing   45000  4500.0
3  Diana         IT   28   Engineer   80000  8000.0
4    Sam        Biz   22      Sales   48000  4800.0

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam", "John"],
    "Age":        [26, None, 20, 28, None, 35],
    "Occupation": ["Engineer", "Sales", None, "Engineer", "Sales", None],
    "Salary":     [70000, 50000, None, 80000, None, 60000],
    "Experience": [3, None, 1, None, 2, 10]
})

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       6 non-null      str
 1   Age         4 non-null      float64
 2   Occupation  4 non-null      str
 3   Salary      4 non-null      float64
 4   Experience  4 non-null      float64
dtypes: float64(3), str(2)
memory usage: 372.0 bytes

In [11]:
df.isnull().sum() / len(df) * 100

Names          0.000000
Age           33.333333
Occupation    33.333333
Salary        33.333333
Experience    33.333333
dtype: float64

In [12]:
df['Occupation'].fillna("Unknown",inplace=True)

C:\Users\Ritik\AppData\Local\Temp\ipykernel_10424\2327441180.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Occupation'].fillna("Unknown",inplace=True)

0    Engineer
1       Sales
2     Unknown
3    Engineer
4       Sales
5     Unknown
Name: Occupation, dtype: str

In [13]:
df

   Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   NaN      Sales  50000.0         NaN
2  Ronit  20.0        NaN      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   NaN      Sales      NaN         2.0
5   John  35.0        NaN  60000.0        10.0

In [16]:
df['Age']=df['Age'].fillna(0)

In [17]:
df

   Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   0.0      Sales  50000.0         NaN
2  Ronit  20.0        NaN      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   0.0      Sales      NaN         2.0
5   John  35.0        NaN  60000.0        10.0

In [19]:
df['Occupation'].mode()

0    Engineer
1       Sales
Name: Occupation, dtype: str

In [20]:
df['Names'].mode()

0    Diana
1     John
2    Parth
3    Ritik
4    Ronit
5      Sam
Name: Names, dtype: str

In [24]:
df['Occupation'].value_counts()

Occupation
Engineer    2
Sales       2
Name: count, dtype: int64