In [8]:
!pip install pandas 
!pip install numpy

import numpy as np

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.0.2)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

ModuleNotFoundError: No module named 'numpy'

In [1]:
import pandas as pd
import numpy as np

In [2]:



df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam", "John"],
    "Age":        [26, None, 20, 28, None, 35],
    "Occupation": ["Engineer", "Sales", None, "Engineer", "Sales", None],
    "Salary":     [70000, 50000, None, 80000, None, 60000],
    "Experience": [3, None, 1, None, 2, 10]
})

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       6 non-null      str
 1   Age         4 non-null      float64
 2   Occupation  4 non-null      str
 3   Salary      4 non-null      float64
 4   Experience  4 non-null      float64
dtypes: float64(3), str(2)
memory usage: 372.0 bytes

In [4]:
df.info

<bound method DataFrame.info of    Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   NaN      Sales  50000.0         NaN
2  Ronit  20.0        NaN      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   NaN      Sales      NaN         2.0
5   John  35.0        NaN  60000.0        10.0>

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       6 non-null      str
 1   Age         4 non-null      float64
 2   Occupation  4 non-null      str
 3   Salary      4 non-null      float64
 4   Experience  4 non-null      float64
dtypes: float64(3), str(2)
memory usage: 372.0 bytes

In [7]:
df.describe()

             Age        Salary  Experience
count   4.000000      4.000000    4.000000
mean   27.250000  65000.000000    4.000000
std     6.184658  12909.944487    4.082483
min    20.000000  50000.000000    1.000000
25%    24.500000  57500.000000    1.750000
50%    27.000000  65000.000000    2.500000
75%    29.750000  72500.000000    4.750000
max    35.000000  80000.000000   10.000000

In [9]:
df.dtypes

Names             str
Age           float64
Occupation        str
Salary        float64
Experience    float64
dtype: object

In [10]:
df

   Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   NaN      Sales  50000.0         NaN
2  Ronit  20.0        NaN      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   NaN      Sales      NaN         2.0
5   John  35.0        NaN  60000.0        10.0

In [14]:
df.isnull().sum()

Names         0
Age           2
Occupation    2
Salary        2
Experience    2
dtype: int64

In [15]:
df['Occupation']=df['Occupation'].fillna("Unknown")
df

   Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   NaN      Sales  50000.0         NaN
2  Ronit  20.0    Unknown      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   NaN      Sales      NaN         2.0
5   John  35.0    Unknown  60000.0        10.0

In [16]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

   Names    Age Occupation   Salary  Experience
0  Ritik  26.00   Engineer  70000.0         3.0
1  Parth  27.25      Sales  50000.0         NaN
2  Ronit  20.00    Unknown      NaN         1.0
3  Diana  28.00   Engineer  80000.0         NaN
4    Sam  27.25      Sales      NaN         2.0
5   John  35.00    Unknown  60000.0        10.0

In [23]:
df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam", "John"],
    "Department": ["IT", "Sales", "IT", "Sales", "IT", "Sales"],
    "Age":        [26, 26, 20, 28, 22, 35],
    "Salary":     [70000, 50000, 45000, 80000, 48000, 60000],
    "Experience": [3, 5, 1, 8, 2, 10]
})

In [24]:
df

   Names Department  Age  Salary  Experience
0  Ritik         IT   26   70000           3
1  Parth      Sales   26   50000           5
2  Ronit         IT   20   45000           1
3  Diana      Sales   28   80000           8
4    Sam         IT   22   48000           2
5   John      Sales   35   60000          10

In [25]:
df.groupby('Department')['Salary'].mean()

Department
IT       54333.333333
Sales    63333.333333
Name: Salary, dtype: float64

In [ ]:
df.loc[df[df['Age'] == 26]['Salary'].idxmax()]

Names         Ritik
Department       IT
Age              26
Salary        70000
Experience        3
Name: 0, dtype: object

In [34]:
df.groupby("Department")

In [41]:
df = pd.DataFrame({
    "Names": ["Ritik","Parth","Ronit","Diana","Sam"] , 
    "Age": [26,None,20,28,None] ,
    "Salary": [70000,50000,None,80000,None]
})
df

   Names   Age   Salary
0  Ritik  26.0  70000.0
1  Parth   NaN  50000.0
2  Ronit  20.0      NaN
3  Diana  28.0  80000.0
4    Sam   NaN      NaN

In [42]:
df.isnull().sum() / len(df) * 100

Names      0.0
Age       40.0
Salary    40.0
dtype: float64

In [43]:
df.describe()

             Age        Salary
count   3.000000      3.000000
mean   24.666667  66666.666667
std     4.163332  15275.252317
min    20.000000  50000.000000
25%    23.000000  60000.000000
50%    26.000000  70000.000000
75%    27.000000  75000.000000
max    28.000000  80000.000000

In [44]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

   Names        Age   Salary
0  Ritik  26.000000  70000.0
1  Parth  24.666667  50000.0
2  Ronit  20.000000      NaN
3  Diana  28.000000  80000.0
4    Sam  24.666667      NaN

In [45]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

   Names        Age   Salary
0  Ritik  26.000000  70000.0
1  Parth  24.666667  50000.0
2  Ronit  20.000000  70000.0
3  Diana  28.000000  80000.0
4    Sam  24.666667  70000.0

In [48]:
df1=pd.DataFrame([100, None, None, 400, None, 600],columns=['Random'])
df2=pd.DataFrame([100, None, None, 400, None, 600],columns=['Random'])
df1

   Random
0   100.0
1     NaN
2     NaN
3   400.0
4     NaN
5   600.0

In [49]:
df1=df1.ffill()
df1

   Random
0   100.0
1   100.0
2   100.0
3   400.0
4   400.0
5   600.0

In [50]:
df2=df2.bfill()
df2

   Random
0   100.0
1   400.0
2   400.0
3   400.0
4   600.0
5   600.0

In [51]:
df3=pd.DataFrame([10, None, None, 40, None, 60])
df3

      0
0  10.0
1   NaN
2   NaN
3  40.0
4   NaN
5  60.0

In [52]:
df3=df3.interpolate()

In [53]:
df3

      0
0  10.0
1  20.0
2  30.0
3  40.0
4  50.0
5  60.0

In [54]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam", "John"],
    "Age":        [26, None, 20, 28, None, 35],
    "Occupation": ["Engineer", "Sales", None, "Engineer", "Sales", None],
    "Salary":     [70000, 50000, None, 80000, None, 60000],
    "Experience": [3, None, 1, None, 2, 10]
})

In [55]:
df

   Names   Age Occupation   Salary  Experience
0  Ritik  26.0   Engineer  70000.0         3.0
1  Parth   NaN      Sales  50000.0         NaN
2  Ronit  20.0        NaN      NaN         1.0
3  Diana  28.0   Engineer  80000.0         NaN
4    Sam   NaN      Sales      NaN         2.0
5   John  35.0        NaN  60000.0        10.0

In [56]:
df=df.fillna({
    'Age': df['Age'].mean(),
    'Salary': df.Salary.median(),
    'Occupation': df.Occupation.fillna("Unknown")
})
df

   Names    Age Occupation   Salary  Experience
0  Ritik  26.00   Engineer  70000.0         3.0
1  Parth  27.25      Sales  50000.0         NaN
2  Ronit  20.00    Unknown  65000.0         1.0
3  Diana  28.00   Engineer  80000.0         NaN
4    Sam  27.25      Sales  65000.0         2.0
5   John  35.00    Unknown  60000.0        10.0

In [57]:
dftemp=pd.DataFrame({
    "Department": ["IT","Sales","IT","Sales","IT","Sales"], 
    "Salary": [70000,50000,45000,80000,48000,60000]
})

In [58]:
dftemp

  Department  Salary
0         IT   70000
1      Sales   50000
2         IT   45000
3      Sales   80000
4         IT   48000
5      Sales   60000

In [63]:
dftemp.groupby("Department")['Salary'].agg(['max','min','mean','sum'])

              max    min          mean     sum
Department
IT          70000  45000  54333.333333  163000
Sales       80000  50000  63333.333333  190000

In [64]:
dftemp

  Department  Salary
0         IT   70000
1      Sales   50000
2         IT   45000
3      Sales   80000
4         IT   48000
5      Sales   60000

In [74]:
df = pd.DataFrame({
    "Names":      ["Ritik", "Parth", "Ronit", "Diana", "Sam", "John"],
    "Department": ["IT", "Sales", "IT", "Sales", "IT", "Sales"],
    "Age":        [26, 26, 20, 28, 22, 35],
    "Salary":     [70000, 50000, 45000, 80000, 48000, 60000],
    "Experience": [3, 5, 1, 8, 2, 10]
})
df

   Names Department  Age  Salary  Experience
0  Ritik         IT   26   70000           3
1  Parth      Sales   26   50000           5
2  Ronit         IT   20   45000           1
3  Diana      Sales   28   80000           8
4    Sam         IT   22   48000           2
5   John      Sales   35   60000          10

In [75]:
# df['Avg_salary_dep']=
df.groupby('Department')['Salary'].mean()

Department
IT       54333.333333
Sales    63333.333333
Name: Salary, dtype: float64

In [77]:
df['Average+dept_sal']=df.groupby('Department')['Salary'].transform('mean')
df

   Names Department  Age  Salary  Experience  Average+dept_sal
0  Ritik         IT   26   70000           3      54333.333333
1  Parth      Sales   26   50000           5      63333.333333
2  Ronit         IT   20   45000           1      54333.333333
3  Diana      Sales   28   80000           8      63333.333333
4    Sam         IT   22   48000           2      54333.333333
5   John      Sales   35   60000          10      63333.333333